### PR TITLE
use agent and remove unused pool variable

### PR DESCRIPTION
**Pull request by ErickSegaar**
## Problem
The documentation describes the use of a POOL variable in the library to use your hosted agent. This POOL variable is actually never used and the vmimage is set hard for the pipeline.

image

## Solution
Replaced the hard reference with the $(Agent) that is being used by other parts of the code and is defined in your second library

## Tests
Run the 02 pipeline

## Notes
Should also be removed from the documentation cause it is doing nothing [documentaion](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/automation-configure-devops#common-variables)

### CODE REVIEW

**Comment by KimForss** [comment]
Hi @ErickSegaar 

The POOL parameter is used for the automatic configuration of the deployer to automatically register the deployer as an agent.

https://github.com/Azure/sap-automation/blob/dcd55edef8754a893e12c2f839ca5c3798415da0/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl#L484

I can make that more visible in the documentation.

//Kimmo

**Comment by ErickSegaar** [comment]
> 

Ok, missed that one when I searched for it. Shall I update the PR with the POOL environment variable back in it. But remain the $(agent) for the running of the pipeline?

**Comment by KimForss** [comment]
Yes please
//Kimmo

**Comment by ErickSegaar** [comment]
Ok cleaned it up

**Review by KimForss — APPROVED** [review]

**Pull request merged**
